config/routes.rb
Rails.application.routes.draw do
  get 'movies', to:'movies#index', as: 'movies'
  get 'movies/new', to: 'movies#new'
  post 'movies', to: 'movies#create'
  get 'movies/:id/', to: 'movies#show', as: 'movie'
  get 'movies/:id/edit', to: 'movies#edit', as: 'edit_movie'
  patch 'movies/:id', to: 'movies#update'
  delete 'movies/:id', to: 'movies#destroy', as: 'destroy_movie'
  root 'movies#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  def index
    @movies = Movie.all
  end

  def show
    if @movie.favorite == true
      @favorite = 'Favorita'
    else
      @favorite = 'General'
    end
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to movie_path(@movie)
    else
      'Algo salió mal'
    end

  end

  def edit

  end

  def update
    @movie.update(movie_params)
    redirect_to movie_path(@movie)

  end

  def destroy
    @movie.delete
    redirect_to movies_path
  end

  private
  def set_movie
    @movie = Movie.find(params[:id])
  end

  def movie_params
    params.require(:movie).permit(:name, :year, :favorite)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrepCrudManual</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'solar.min' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/movies/edit.html.erb
<h3>Editar película:</h3>
<%= form_with model: @movie, local: true do |form| %>
  <div class="row">
    <div class="col">
      <%= form.label 'Nombre' %>
      <%= form.text_field :name, placeholder:'Nombre', class:'form-control' %>
    </div>
    <div class="col">
      <%= form.label 'Año' %>
      <%= form.number_field :year, placeholder:'Año', class:'form-control' %>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col">
      <%= form.label 'Añadir a favoritos' %>
      <%= form.check_box :favorite %>
    </div>
  </div>
  <br>
  <%= form.submit 'Enviar', class:'btn btn-success' %>
  <% end %>

app/views/movies/index.html.erb
<h1>Películas:</h1>
<br>
<h3>Favoritas:</h3>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nombre</th>
      <th scope="col">Año</th>
      <th> </th>
    </tr>
  </thead>
  <tbody>
    <% @movies.each do |movie| %>
      <% if movie.favorite == true %>
        <tr>
          <th scope="row"><%= movie.id%></th>
          <td><%= movie.name %></td>
          <td><%= movie.year %></td>
          <td>
            <%= link_to 'Ver',  movie_path(movie),  class: 'btn btn-success' %>
            <%= link_to 'Editar',  edit_movie_path(movie),  class: 'btn btn-warning' %>
            <%= link_to 'Eliminar', movie, method: :delete, class: 'btn btn-danger' %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<br>
<h3>General:</h3>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nombre</th>
      <th scope="col">Año</th>
      <th> </th>
    </tr>
  </thead>
  <tbody>
    <% @movies.each do |movie| %>
      <% if movie.favorite == false %>
        <tr>
          <th scope="row"><%= movie.id%></th>
          <td><%= movie.name %></td>
          <td><%= movie.year %></td>
          <td>
            <%= link_to 'Ver',  movie_path(movie),  class: 'btn btn-success' %>
            <%= link_to 'Editar',  edit_movie_path(movie),  class: 'btn btn-warning' %>
            <%= link_to 'Eliminar', destroy_movie_path(movie), method: :delete, class: 'btn btn-danger' %>
          </td>
        </tr>
        <% end %>
      <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Nueva película', movies_new_path, class: 'btn btn-info' %>

app/views/movies/new.html.erb
<h3>Nueva película:</h3>
<%= form_with model: @movie, local: true do |form| %>
  <div class="row">
    <div class="col">
      <%= form.label 'Nombre' %>
      <%= form.text_field :name, placeholder:'Nombre', class:'form-control' %>
    </div>
    <div class="col">
      <%= form.label 'Año' %>
      <%= form.number_field :year, placeholder:'Año', class:'form-control' %>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col">
      <%= form.label 'Añadir a favoritos' %>
      <%= form.check_box :favorite %>
    </div>
  </div>
  <br>
  <%= form.submit 'Enviar', class:'btn btn-success' %>
  <% end %>

app/views/movies/show.html.erb
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= @movie.name %></h5>
    <h6 class="card-subtitle mb-2 text-muted"><%= @favorite %></h6>
    <p class="card-text"><%= @movie.year %></p>
    <%= link_to 'Volver', movies_path, class:'btn btn-info'%>
    <%= link_to 'Editar', edit_movie_path , class:'btn btn-warning'%>
  </div>
</div>